"""Añade campos para abono inicial

Revision ID: 8d0a6f212312
Revises: 62cff32d842e
Create Date: 2025-10-20 13:58:54.483824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0a6f212312'
down_revision = '62cff32d842e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_articulo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('abono_inicial', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.drop_column('abono_inicial')
        batch_op.drop_column('valor_articulo')

    # ### end Alembic commands ###
